import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function productosSeeder() {
  console.log('Seeding productos...');

  await prisma.producto.createMany({
    data: [
      {
        id: 1,
        codigo: 'AP-0001',
        codigoTienda: 'ST-001',
        codigoReferencia: 'REF-ALT1234',
        descripcion: 'Alternador para Toyota Corolla 2015',
        unidad: 'pieza',
        marca: 'Bosch',
        precioCompra: 120.5,
        precioVenta: 185.99,
        alertaStockBajo: 5,
        imagen: 'https://example.com/img/alternador.jpg',
        beneficio: 65.49,
        medidas: '15x12x10 cm',
        usuarioCreadorId: 1,
        usuarioActualizadorId: 1,
        createdAt: '2025-05-20T10:00:00Z',
        updatedAt: '2025-05-20T10:00:00Z',
        deletedAt: null,
      },
      {
        id: 2,
        codigo: 'AP-0002',
        codigoTienda: 'ST-002',
        codigoReferencia: 'REF-FLT5678',
        descripcion: 'Filtro de aceite Honda Civic 2018',
        unidad: 'pieza',
        marca: 'Mann-Filter',
        precioCompra: 8.0,
        precioVenta: 12.5,
        alertaStockBajo: 10,
        imagen: null,
        beneficio: 4.5,
        medidas: '10x8x8 cm',
        usuarioCreadorId: 2,
        usuarioActualizadorId: null,
        createdAt: '2025-05-20T10:00:00Z',
        updatedAt: '2025-05-20T10:00:00Z',
        deletedAt: null,
      },
      {
        id: 3,
        codigo: 'AP-0003',
        codigoTienda: 'ST-001',
        codigoReferencia: 'REF-FRJ4321',
        descripcion: 'Juego de frenos delanteros Ford F-150',
        unidad: 'juego',
        marca: 'ACDelco',
        precioCompra: 75.0,
        precioVenta: 110.0,
        alertaStockBajo: 3,
        imagen: 'https://example.com/img/frenos.jpg',
        beneficio: 35.0,
        medidas: '25x20x10 cm',
        usuarioCreadorId: 3,
        usuarioActualizadorId: 3,
        createdAt: '2025-05-20T10:00:00Z',
        updatedAt: '2025-05-20T10:00:00Z',
        deletedAt: null,
      },
      {
        id: 4,
        codigo: 'AP-0004',
        codigoTienda: 'ST-003',
        codigoReferencia: 'REF-LMP9876',
        descripcion: 'Lámpara delantera Nissan Versa 2020',
        unidad: 'pieza',
        marca: 'Philips',
        precioCompra: 60.0,
        precioVenta: 95.0,
        alertaStockBajo: 4,
        imagen: null,
        beneficio: 35.0,
        medidas: null,
        usuarioCreadorId: 4,
        usuarioActualizadorId: 1,
        createdAt: '2025-05-20T10:00:00Z',
        updatedAt: '2025-05-20T10:00:00Z',
        deletedAt: null,
      },
      {
        id: 5,
        codigo: 'AP-0005',
        codigoTienda: 'ST-001',
        codigoReferencia: 'REF-BAT0012',
        descripcion: 'Batería 12V 70Ah para vehículos',
        unidad: 'pieza',
        marca: 'LTH',
        precioCompra: 90.0,
        precioVenta: 130.0,
        alertaStockBajo: 2,
        imagen: 'https://example.com/img/bateria.jpg',
        beneficio: 40.0,
        medidas: '30x20x20 cm',
        usuarioCreadorId: 2,
        usuarioActualizadorId: 2,
        createdAt: '2025-05-20T10:00:00Z',
        updatedAt: '2025-05-20T10:00:00Z',
        deletedAt: null,
      },
    ],
    skipDuplicates: true,
  } as any);

  console.log('Seeding de productos terminado.');
}
